(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k0=function(a){a.W("cardstatechange",a.Rh()&&a.Pl()?1:0)},l0=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},IVa=function(a){var b=g.$k(a);
a=g.cl(a);return new g.Pk(b.x,b.y,a.width,a.height)},JVa=function(a){return Math.pow(a,3)},KVa=function(a){return 3*a*a-2*a*a*a},o0=function(a){a=g.Ra(a);
delete m0[a];g.Le(m0)&&n0&&n0.stop()},MVa=function(){n0||(n0=new g.K(function(){LVa()},20));
var a=n0;a.isActive()||a.start()},LVa=function(){var a=g.Va();
g.Be(m0,function(b){NVa(b,a)});
g.Le(m0)||MVa()},p0=function(a,b,c,d){g.ho.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.P=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},NVa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;OVa(a,a.progress);1==a.progress?(a.j=0,o0(a),a.onFinish(),a.Qy()):a.isPlaying()&&a.CE()},OVa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.P[c]-a.u[c])*b+a.u[c]},PVa=function(a,b){g.ve.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},q0=function(a,b,c,d,e){p0.call(this,b,c,d,e);
this.element=a},r0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
q0.call(this,a,b,c,d,e)},s0=function(a){g.I.call(this);
this.u=a||window;this.j=[]},t0=function(a){return a.baseUrl||null},u0=function(a,b){return g.Nl(g.ck(a,b),function(c){return!!c})},QVa=function(a,b,c){function d(ba){var pa=ba.hovercardButton;
if(!pa)return null;pa=pa.subscribeButtonRenderer;if(!pa)return null;var Ya=f(pa.unsubscribedButtonText),Ua=f(pa.subscribedButtonText);if(pa.subscribed){var nb=f(pa.subscriberCountWithUnsubscribeText);var ob=f(pa.subscriberCountText)}else nb=f(pa.subscriberCountText),ob=f(pa.subscriberCountWithSubscribeText);var fc=null;if(ba.signinEndpoint){fc=l0(ba,"signinEndpoint","webNavigationEndpointData","url");if(!fc){var cb,Db,pb;fc=null==(cb=pa.signInEndpoint)?void 0:null==(Db=cb.commandMetadata)?void 0:
null==(pb=Db.webCommandMetadata)?void 0:pb.url}if(!fc)return null}return Ya&&(Ua||fc)?{subscribed:pa.subscribed,subscribeText:Ya,subscribeCount:nb,unsubscribeText:Ua,unsubscribeCount:ob,enabled:pa.enabled,signinUrl:fc,classic:ba.useClassicSubscribeButton}:null}
function e(ba){if(ba){var pa=[],Ya=ba.videoId;Ya&&pa.push("v="+Ya);(Ya=ba.playlistId)&&pa.push("list="+Ya);(ba=ba.startTimeSeconds)&&pa.push("t="+ba);return"/watch?"+pa.join("&")}}
function f(ba){if(!ba)return null;var pa=ba.simpleText;return pa?pa:ba.runs?g.ck(ba.runs,function(Ya){return Ya.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,u=null,x=null,y=!1,z=null,D=null,H=null,G=null,L=null,aa=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,u=f(b.playlistLength);
else if("CHANNEL"===h){if(y=l0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((H=l0(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=l0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=l0(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:
null,sa="";if(b.metadata){var xa=f(b.metadata);xa&&(sa=xa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:sa,callToAction:f(b.callToAction),fN:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:u,channelId:x,subscribeButton:z,subscribersText:D,isSubscribe:y,targetUrl:m||null,UW:n,sessionData:M?{itct:M}:null,E0:q,
Ww:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:u0(b.impressionUrls||[],t0),JW:u0(b.hovercardShowUrls||[],t0),clickUrls:u0(l.loggingUrls||[],t0),visualElement:g.zu(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:aa||null}},v0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:u0(a.impressionUrls||[],t0),elements:u0(a.elements||[],function(d,e){return QVa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.zu(a.trackingParams));return c},w0=function(a){g.PI.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.P=!0;this.I=0;a=a.S();this.isEmbedded=g.YA(a)||g.bB(a);this.U=a.experiments.bb("web_rounded_thumbnails");this.events=new g.ez(this);g.J(this,this.events);this.events.N(this.player,g.xv("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.yv("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.ub);this.events.N(window,"focus",this.A_);this.load();var b=g.tg("STYLE");(g.lg("HEAD")[0]||
document.body).appendChild(b);g.te(this,function(){g.xg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},RVa=function(a){return a.player.getVideoData().D?"current":a.isEmbedded?"new":"current"},x0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},SVa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=v0(f,RVa(a))));y0(a,f)},
urlParams:{v:c},withCredentials:!0};a.isEmbedded&&(c.urlParams.ptype="embedded");var d=b.Jr;d&&(c.postParams={ad_tracking:d});if(b=g.bya(b))if(b=g.Bf(b),b=g.vf(b))a.B=g.gq(b,c)},y0=function(a,b,c){c=void 0===c?!0:c;
a.player.zf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&TVa(a);c=[];d=new g.vv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().isMobile||(a.u=new g.W({F:"div",L:"ytp-ce-shadow"}),g.zI(a.player,a.u.element,4),a.C=new g.ZG(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=UVa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.zI(a.player,f.element,4);var h=new g.vv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);VVa(a,
f,e)}else g.wu(new g.rr("buildEndscreenElement null",e))}a.player.Sd(c);a.ub()}},TVa=function(a){var b=g.Fu(),c=g.Gu();
c&&b&&a.endscreen.visualElement&&g.Ku(void 0,c,b,[a.endscreen.visualElement])},UVa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Aa:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:z0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:A0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Aa:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.lo(b.title||"")},X:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
X:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Aa:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:z0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:A0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Aa:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.lo(b.title||"")},X:b.title},{F:"div",L:"ytp-ce-playlist-count",
R:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",X:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Aa:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"a",Aa:["ytp-ce-channel-title","ytp-ce-link"],T:{href:A0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.lo(b.title||"")},X:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",R:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",X:b.subscribersText}:"",b.metadata?{F:"div",Aa:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],X:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:z0(b)}]};c=new g.W(c);var d=g.mg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.S().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.UJ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Aa:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.lo(b.title||"")},X:b.title},{F:"div",L:"ytp-ce-website-metadata",X:b.metadata},{F:"a",Aa:["ytp-ce-website-goto","ytp-ce-link"],T:{href:A0(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:z0(b)},{F:"div",L:"ytp-ce-expanding-icon",T:WVa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",R:[{F:"div",L:"ytp-ce-merchandise-price",X:b.productPrice}]},b.additionalFeesText&&c.R.push({F:"div",L:"ytp-ce-merchandise-additional-fees",X:b.additionalFeesText})),a={F:"div",Aa:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.lo(b.title||"")},X:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",X:b.metadata},{F:"a",Aa:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:A0(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:z0(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
R:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",X:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.N(c.element,"ytp-ce-placeholder");return c},z0=function(a){if(a.fN)var b=a.fN.thumbnails;
return WVa(b?b[b.length-1].url:null)},WVa=function(a){return a?{style:"background-image: url("+a+")"}:{}},VVa=function(a,b,c){function d(m){m&&(b.Ka("blur",function(){"none"!=m.style.display&&a.P&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),B0(a,c.id,!0)):(g.Hn(b.element,"ytp-ce-force-expand"),g.Hn(b.element,"ytp-ce-element-hover"),B0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ka("mouseenter",function(){C0(a,b,c)});
b.Ka("mouseleave",function(){D0(a,b,c)});
a.player.S().isMobile||b.Ka("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ka("click",function(m){XVa(a,c,m)});
b.Ka("keypress",function(m){XVa(a,c,m)});
b.Ka("focus",function(){C0(a,b,c)});
b.Ka("blur",function(){D0(a,b,c)});
b.Ka("touchstart",function(){C0(a,b,c)});
var l=g.og("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Hn(b.element,"ytp-ce-element-hover");g.Hn(b.element,"ytp-ce-force-expand")});
b.Ka("keydown",function(m){a.P=9===m.keyCode&&!m.shiftKey});
d(g.og("ytp-sb-subscribe",b.element));d(g.og("ytp-sb-unsubscribe",b.element));b.Ka("focus",f);b.Ka("blur",h)},XVa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Fn(d,"ytp-ce-element");){g.Fn(d,"subscribe-label")&&E0(a,b);
if(g.Fn(d,"ytp-ce-channel-subscribe"))return;d=g.yg(d)}if(!d||g.Fn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])D0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.E0)E0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Bf(A0(a,b.targetUrl)),g.yH(g.vf(c),void 0,b.sessionData);else{var e=g.qB(a.player.S())||a.player.getVideoData().D,f=function(){var h=A0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Tp(h);e&&n&&(n.v||n.list)?
a.player.ll(n.v,l,n.list,!1,void 0,m||void 0):g.xH(h,l)};
E0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},A0=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.AB(a)+b}else return"";return b},C0=function(a,b,c){g.Fn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.S().isMobile?(new g.K(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),F0(a,c.JW),B0(a,c.id,!0))},D0=function(a,b,c){g.Hn(b.element,"ytp-ce-element-hover");
g.Hn(b.element,"ytp-ce-force-expand");B0(a,c.id,!1)},B0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},F0=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||x0(a))c&&c();else{b=YVa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.As(b[a],d)}},E0=function(a,b,c){F0(a,b.clickUrls,c);
(a=g.Gu())&&b.UW&&g.Qu(a,b.visualElement)},YVa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(ZVa(b[d],c));return a},ZVa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},$Va=function(a){return"string"===typeof a?a:""},G0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},aWa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},H0=function(a){return a.value?a.value:null},I0=function(a){if(!a)return null;
var b=g.Bf($Va(a.value));b=g.vf(b);if(!b)return null;var c=G0(a.target,bWa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new aWa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},cWa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},fWa=function(a){if(!a)return null;
var b=G0(a.type,dWa),c=G0(a.trigger,eWa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=I0(a?a:null);return b?new cWa(b,c,a):null},gWa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},iWa=function(a){return(a=hWa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},hWa=function(a,b){return g.Ub(a.action,b)},jWa=function(a,b){this.context=a;
this.j=b},K0=function(a){return a.customMessage?J0("div","iv-card-message",a.customMessage):""},L0=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},R:c}},M0=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(J0("li","",c.value));return{F:"ul",L:"iv-card-meta-info",R:b}},J0=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.lo(c);return{F:a,T:b,X:c}},kWa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ix&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ix+");");c.dir=g.lo(a.customMessage);var d=[{F:"span",X:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Aa:b,T:c,R:d}},N0=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},lWa=function(a,b){this.merchant=a;
this.price=b},mWa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},nWa=function(a,b){return b?b:mWa(a)?"current":"new"},O0=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.ib=!1;this.Qa=new Map;this.Ra=new Map;this.context.G.addEventListener(g.xv("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.yv("annotations_module"),function(d){(d=c.Ra.get(d))&&d.apply(c)})},P0=function(a,b,c,d,e,f,h){a.context.j.Ka(b,"click",function(l){a.DE(c,d,e,f||[],h||0,l)});
a.context.j.Ka(b,"touchstart",function(){a.ib=!1});
a.context.j.Ka(b,"touchmove",function(){a.ib=!0})},oWa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Q0=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},T0=function(a,b,c){O0.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ja=this.Kb=this.B=this.isInitialized=!1;this.ma=null;this.cards=[];this.sb=this.P=this.Ga=this.D=this.Pa=this.j=null;this.V=[];this.Z=this.J=this.Ze=this.Ca=null;this.I=0;this.xa=new g.K(function(){},c.environmentData.Ue?4E3:3E3);
g.J(this,this.xa);this.Za=new g.K(function(){});
g.J(this,this.Za);this.ea=new jWa(c,function(e,f,h,l,m,n){P0(d,e,f,h,l,m,n)});
this.U=new g.W({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},R:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},R:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Aa:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.J(this,this.U);this.C=this.U.element;this.Ya=new g.ZG(this.U,330);g.J(this,this.Ya);this.Gb=g.og("iv-drawer-header-text",this.C);this.u=g.og("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&R0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.B)&&S0(d)});
this.G.addEventListener("videodatachange",this.yp.bind(this))},pWa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){R0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){S0(a)});
var c=b.headerText;g.Cg(a.Gb,c);a.P&&a.P.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.zu(b.trackingParams);a.J=g.zu(b.closeTrackingParams);a.Ze=g.zu(b.iconTrackingParams)},qWa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.S().experiments.bb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Cv(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ql:null,lj:d.trackingParams?g.zu(d.trackingParams):null,Ze:e&&e.trackingParams?g.zu(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,ix:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};U0(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Cv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:V0(a,
c,b,d),sponsored:!1,tracking:Q0(d,e,d.command),Ql:d.trackingParams?g.zu(d.trackingParams):null,lj:e.trackingParams?g.zu(e.trackingParams):null,Ze:f&&f.trackingParams?g.zu(f.trackingParams):null,imageUrl:W0(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Cv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ix:null,title:d.title?g.Cv(d.title):"",customMessage:d.callToAction?g.Cv(d.callToAction):"",url:d.command.urlEndpoint.url?I0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};U0(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Cv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:V0(a,
c,b,d),sponsored:!1,tracking:Q0(d,e,d.endpoint),Ql:d.trackingParams?g.zu(d.trackingParams):null,lj:e.trackingParams?g.zu(e.trackingParams):null,Ze:f&&f.trackingParams?g.zu(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Cv(d.customText):null,profileImageUrl:W0(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Cv(d.channelName):"",metaInfo:[d.subscriberCountText?g.Cv(d.subscriberCountText):""],url:I0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};U0(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Cv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:V0(a,c,b,d),sponsored:!1,tracking:Q0(d,e,d.action),Ql:d.trackingParams?g.zu(d.trackingParams):null,lj:e.trackingParams?g.zu(e.trackingParams):null,Ze:f&&f.trackingParams?g.zu(f.trackingParams):null,thumbnailImageUrl:W0(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Cv(d.customMessage):null,playlistVideoCount:g.Cv(d.playlistVideoCount),title:d.playlistTitle?g.Cv(d.playlistTitle):"",metaInfo:[d.channelName?
g.Cv(d.channelName):"",d.videoCountText?g.Cv(d.videoCountText):""],url:I0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:oWa(d.action)}),onClickCommand:null};U0(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Cv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:V0(a,c,b,d),sponsored:!1,tracking:Q0(d,e,d.action),Ql:d.trackingParams?g.zu(d.trackingParams):null,lj:e.trackingParams?g.zu(e.trackingParams):null,Ze:f&&f.trackingParams?g.zu(f.trackingParams):null,thumbnailImageUrl:W0(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Cv(d.lengthString):null,customMessage:d.customMessage?g.Cv(d.customMessage):null,title:d.videoTitle?g.Cv(d.videoTitle):"",metaInfo:[d.channelName?
g.Cv(d.channelName):"",d.viewCountText?g.Cv(d.viewCountText):""],isLiveNow:!!d.badge,url:I0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:oWa(d.action)}),onClickCommand:null};U0(a,b)}a.I++},W0=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},V0=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},sWa=function(a,b){if(b=rWa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.xg(b.wF),g.ac(a.cards,b),a.FA(),X0(a)},R0=function(a,b,c){if(!a.B){a.Ya.show();
a.Pa=new g.K(function(){g.N(a.context.G.getRootNode(),g.uO.IV_DRAWER_OPEN)},0);
a.Pa.start();a.ma=g.bt(a.u,"mousewheel",function(h){a.xa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Gu();d&&a.Ca&&a.J&&g.Ou(d,[a.Ca,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.PO||(f.PO=!0,tWa(a.context.logger,f.card.tracking.impression,b)),d&&g.Ou(d,[f.card.Ql]);k0(a.G);c&&(a.D=new g.K(function(){a.Ga=a.P;a.sb.focus()},330),a.D.start())}},S0=function(a){a.B&&(a.Ya.hide(),g.ct(a.ma),a.ma=null,g.Hn(a.context.G.getRootNode(),g.uO.IV_DRAWER_OPEN),a.B=!1,k0(a.G),a.D&&a.D.stop(),a.D=new g.K(function(){a.Ga&&(a.Ga.focus(),a.Ga=null)},330),a.D.start())},
vWa=function(a){g.Gn(a.element,[g.uO.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.zI(a.G,a.C,5);uWa(a);a.P=g.og("ytp-cards-button",a.G.getRootNode());a.sb=g.og("iv-drawer-close-button",a.C);a.isInitialized=!0},uWa=function(a){var b=g.og("iv-drawer-close-button",a.C);
a.context.j.Ka(b,"click",a.rV,a);a.context.j.Ka(a.u,"touchend",function(){a.xa.start()});
a.context.j.Ka(a.u,"scroll",a.EV,a);a.context.u.subscribe("onHideControls",function(){a.Ja=!0});
a.context.u.subscribe("onShowControls",function(){a.Ja=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ja=g.Fn(a.G.getRootNode(),"ytp-autohide")});
a.V.push(g.wt("iv-button-shown",a.dX,a));a.V.push(g.wt("iv-button-hidden",a.cX,a));a.V.push(g.wt("iv-teaser-shown",a.nU,a));a.V.push(g.wt("iv-teaser-hidden",a.eX,a));a.V.push(g.wt("iv-teaser-clicked",a.mU,a))},wWa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=h[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Z=null,!0}}a.Z=b;return!1},U0=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Z=
b;
var c=!0}else c=!1;if(!c||wWa(a,b))if(c=xWa(a,b)){var d={card:b,wF:c.element,PO:!1};if(!b.onClickCommand){a.isInitialized||vWa(a);sWa(a,b.id);var e=yWa(a,d);g.hc(a.cards,e,0,d);c.ra(a.u,e);a.FA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,X0(a),zWa(a,d),R0(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&AWa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){AWa(a,d)}),X0(a))}},xWa=function(a,b){switch(b.type){case "simple":a=
a.ea;
var c=b.displayDomain?{F:"div",L:"iv-card-image-text",X:b.displayDomain}:void 0;var d=kWa(b);c={F:"div",Aa:["iv-card"],R:[{F:"a",L:"iv-click-target",T:{href:b.url?H0(b.url)||"":""},R:[L0(b.imageUrl,c),{F:"div",L:"iv-card-content",R:[J0("h2",void 0,b.title),d]}]}]};c=new g.W(c);N0(a,g.ng("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ea,c={F:"div",Aa:["iv-card","iv-card-channel"],R:[{F:"a",Aa:["iv-click-target"],T:{href:H0(b.url)||"","data-ytid":b.channelId},R:[L0(b.profileImageUrl),
{F:"div",L:"iv-card-content",R:[K0(b),{F:"h2",L:"iv-card-primary-link",X:b.title},M0(b)]}]}]},c=new g.W(c),N0(a,g.ng("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ea,c={F:"div",Aa:["iv-card","iv-card-playlist"],R:[{F:"a",L:"iv-click-target",T:{href:H0(b.url)||""},R:[L0(b.thumbnailImageUrl,{F:"div",L:"iv-card-image-overlay",R:[{F:"span",L:"iv-card-playlist-video-count",X:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",R:[K0(b),J0("h2","iv-card-primary-link",b.title),M0(b)]}]}]},
c=new g.W(c),N0(a,g.ng("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ea;var e=!g.Yb(b.offers);c=["iv-card"];d="";var f=kWa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",L:"iv-card-offer-price",X:f.price}),f.merchant&&e.push({F:"div",L:"iv-card-offer-merchant",X:f.merchant}),f={F:"div",R:e});e=b.url?H0(b.url)||"":"";c={F:"div",Aa:c,T:{tabindex:"0"},R:[{F:"a",Aa:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",R:[b.sponsored?{F:"div",L:"iv-card-sponsored",R:["Sponsored",{F:"div",L:"iv-ad-info-container",R:[{F:"div",L:"iv-ad-info",X:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",R:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:e},R:[J0("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.tg("span");g.Cg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Gd(d,"adInfo");N0(a,g.ng("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ea,d=b.videoDuration?{F:"span",L:"iv-card-video-duration",X:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Aa:["yt-badge","yt-badge-live"],X:"LIVE NOW"}:null,e={F:"div",Aa:["iv-card","iv-card-video"],R:[{F:"a",L:"iv-click-target",T:{href:(null==(c=b.url)?void 0:H0(c))||""},R:[L0(b.thumbnailImageUrl,d),{F:"div",L:"iv-card-content",R:[K0(b),J0("h2","iv-card-primary-link",b.title),M0(b),f]}]}]},c=new g.W(e),
N0(a,g.ng("iv-click-target",c.element),b,b.url),c;default:return null}},yWa=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},BWa=function(a){return a.j?"productListing"===a.j.card.type:g.dk(a.cards,function(b){return"productListing"===b.card.type})},X0=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",BWa(a))},AWa=function(a,b){if(!g.Fn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Gu(),d=a.j?a.j.card.Ze:a.Ze;
c&&d&&g.Pu(c,[d]);a.j=b;X0(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Jv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.Za.isActive()||((!a.B||!a.xa.isActive()&&a.Ja)&&zWa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},zWa=function(a,b){a.U.kb?(b=new p0([0,
a.u.scrollTop],[0,b.wF.offsetTop],600,KVa),a.context.B.Ka(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ka(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.nG(a.U,!0),a.u.scrollTop=b.wF.offsetTop,g.nG(a.U,!1))},Y0=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},rWa=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},Z0=function(a,b,c){O0.call(this,a,b);
this.annotation=c;this.isActive=!1},CWa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},$0=function(a,b,c){Z0.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},DWa=function(a,b){var c=void 0===c?0:c;
var d=IVa(b).width;g.Yk(b,d);c=new r0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,JVa);g.J(a,c);a.context.B.Ka(c,"begin",function(){g.dl(b,!0)});
c.play()},GWa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Aa:["iv-branding-context-name"],X:b.channel_name}),d=a.createElement({F:"div",Aa:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.UJ(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.ra(d));var f=a.createElement({F:"div",Aa:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Aa:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.dl(h,!1);var l=a.createElement({F:"div",Aa:["branding-context-container-outer"]});l.appendChild(h);g.Sk(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){EWa(a,h,l)},500);
g.J(a,a.B);a.context.j.Ka(a.element,"mouseover",function(){FWa(a,h,l,f,b.image_height)});
a.context.j.Ka(a.element,"mouseout",function(){a.B.start()})}},FWa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.cl(b);a.j||(b.style.width=g.Xk(f.width,!0),c.style.width=g.Xk(f.width,!0));g.Sk(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Sk(d,"right","1px");a.C=!0;g.dl(b,!0);a.D=new g.K(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},EWa=function(a,b,c){g.Hn(a.element,"iv-branding-active");
a.I=new g.K(function(){g.dl(b,!1);a.j||(c.style.width=g.Xk(0,!0))},250);
a.I.start();a.C=!1},HWa=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.environmentData=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},a1=function(a,b,c){Z0.call(this,a,b,c);
var d=this;this.P=this.isCollapsed=this.U=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Aa:["iv-promo-contents"]});this.D=new g.K(function(){d.j.setAttribute("aria-hidden","true");g.dl(d.B,!1);g.dl(d.u,!0)},700,this);
g.J(this,this.D)},IWa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=iWa(a.annotation),f=b.image_url;if(f){var h=a.createElement({F:"div",Aa:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",X:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",X:b.playlist_length.toString()}),h.appendChild(f));e&&P0(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.Nf(f,H0(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",R:[{F:"strong",
X:b.text_line_1}]});var m=a.createElement({F:"p",R:[{F:"span",L:"iv-promo-link",X:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Aa:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Aa:["iv-button","iv-promo-button"],R:[{F:"span",L:"iv-button-content",X:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&P0(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.j,
"iv-click-target");e&&P0(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",R:[{F:"span",X:b.text_line_1}]}),m=a.createElement({F:"p",R:[{F:"strong",X:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Aa:["yt-badge","iv-promo-badge-live"],X:"LIVE NOW"})),g.N(a.j,"iv-click-target"),e&&P0(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Aa:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ka(a.u,"click",function(q){b1(a,5E3,q)});
c.appendChild(a.u);g.dl(a.u,!1);a.context.j.Ka(a.element,"mouseover",a.kW,a);a.context.j.Ka(a.element,"mouseout",a.jW,a);a.context.j.Ka(a.element,"touchend",function(q){b1(a,5E3,q)});
a.B=a.createElement({F:"button",Aa:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ka(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.fW:a.eW,a);c.appendChild(a.B);g.Gn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},b1=function(a,b,c){c.stopPropagation();
JWa(a);KWa(a,b);a.j.focus()},LWa=function(a){a.isCollapsed||a.P||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},JWa=function(a){a.D.stop();
a.isCollapsed&&(g.In(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.dl(a.u,!1),g.dl(a.B,!0))},KWa=function(a,b){a.C||(a.C=g.Xg(function(){c1(this);
LWa(this)},b,a))},c1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},MWa=function(a){this.G=a},tWa=function(a,b,c){b&&(c?d1(a,b.map(function(d){return g.sn(d,c)})):d1(a,b))},d1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.As(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},e1=function(a){g.PI.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new MWa(this.player);this.D=new g.ez(this);this.C=this.Jm=null;this.events=new g.ez(this);this.J=this.j=null;this.P=[];g.J(this,this.D);this.D.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.D.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.D.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.D.N(this.player,"resize",function(d){b.W("resize",d)});
this.D.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.oU,this);this.subscribe("resize",this.uC,this);this.player.S().V.subscribe("vast_info_card_add",this.cQ,this);g.J(this,this.events);this.U=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.W({F:"div",Aa:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.zI(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Aa:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.U);this.B.element.appendChild(a);this.Gs()&&this.load();var c=this.createElement({F:"style"});(g.lg("HEAD")[0]||document.body).appendChild(c);g.te(this,function(){g.xg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},NWa=function(a){a=a.createElement({F:"div",
Aa:["annotation","annotation-type-custom"]});g.dl(a,!1);return a},OWa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.nG(a.u,b);g.nG(a.B,b)},PWa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(PWa(a,e))}return c},SWa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.S().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.aq(h)&&h.responseXML?h.responseXML:null)&&f1(a,h)}};
g.fr()&&(d.onFinish=QWa(a,d.onFinish));d.postParams={ic_only:"1"};RWa(d,c);g.gq(b.Qa,d)}}},RWa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.jx&&(a.postParams.ic_coll=b.jx);b.KA&&(a.postParams.ic_xml=b.KA);b.Lz&&(a.postParams.ic_track=b.Lz)},TWa=function(a){var b=new g.W({F:"div"});
g.dl(b.element,!1);var c=new T0(a.player,b.element,g1(a));g.J(c,b);b.ra(a.u.element);c.xz();return c},g1=function(a){if(!a.J){var b=new s0(a);
g.J(a,b);var c=new g.Yi(a);g.J(a,c);a.J=new HWa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Ie)}return a.J},f1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Gu();if(e){var f=g.Fu();f&&g.Ku(void 0,e,f,[g.zu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=PWa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=G0(f.type,UWa),p=G0(f.style,VWa),q=$Va(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=fWa;if(null==u)var x=null;else if(g.Oa(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new gWa(m,n,p,x,t):null}else e=null}catch(xa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=NWa(f),L=null;switch(l.type){case "branding":if(f.player.S().Kc)break;f.u.element.appendChild(G);L=new $0(G,g1(f),l);break;case "promotion":g.zI(f.player,G,4),L=new a1(G,g1(f),l)}L&&L.xz();if(f=L)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=TWa(a),g.J(a,a.j));if("card"===e.type){c=a.j;var aa=e&&e.data&&e.data.card_type;
f=e.data;if(aa)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,sR:l.teaser_impression,qD:l.teaser_click},G=f.tracking_params||{},L=null,aa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:G.card?g.zu(G.card):null,lj:G.teaser?g.zu(G.teaser):null,Ze:G.icon?g.zu(G.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:I0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};U0(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ql:G.card?g.zu(G.card):null,lj:G.teaser?g.zu(G.teaser):null,Ze:G.icon?g.zu(G.icon):null,thumbnailImageUrl:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:I0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};U0(c,e);break;case "productListing":f.signin_url&&(L=I0({target:"current",value:f.signin_url}));aa=[];for(var M=f.offers||[],sa=0;sa<M.length;sa++)aa.push(new lWa(g.fg(M[sa].merchant),
g.fg(M[sa].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:G.card?g.zu(G.card):null,lj:G.teaser?g.zu(G.teaser):null,Ze:G.icon?g.zu(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ix:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:I0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Qka:L,Pka:f.signin_title?f.signin_title:void 0,Oka:f.signin_message?f.signin_message:void 0,offers:aa,onClickCommand:null};U0(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:G.card?g.zu(G.card):
null,lj:G.teaser?g.zu(G.teaser):null,Ze:G.icon?g.zu(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ix:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:I0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};U0(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:G.card?g.zu(G.card):null,lj:G.teaser?g.zu(G.teaser):null,Ze:G.icon?g.zu(G.icon):null,thumbnailImageUrl:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:I0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},U0(c,e)}}else pWa(a.j,
e);c=!0}}c&&(k0(a.player),a.uC())},WWa=function(a,b){var c=!1;
a.j||(a.j=TWa(a),g.J(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(qWa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Cv(b.headerText):"",g.Cg(c.Gb,d),c.P&&c.P.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.zu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.zu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ze=b.icon.infoCardIconRenderer.trackingParams?
g.zu(b.icon.infoCardIconRenderer.trackingParams):null,k0(a.player),a.uC())},XWa=function(a,b,c,d,e){if(!a.player.S().Kc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new cWa("openUrl","click",new aWa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Cv(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Cv(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Cv(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Cv(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.Cv(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Cv(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new gWa(c,"branding","branding",f,d);l=NWa(a);a.u.element.appendChild(l);f=new $0(l,g1(a),f);f.xz();g.J(f,f);a.I[c]=f}},QWa=function(a,b){return function(){var c=
g.Ea.apply(0,arguments);
a.isDisposed()||a.P.push(g.vn.Sg(function(){b.apply(null,g.v(c))}))}},YWa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.sI.prototype.Jv=g.ea(17,function(a,b){var c=g.fJ(this.fb());c&&c.Jv(a,b)});
var m0={},n0=null;g.Wa(p0,g.ho);g.k=p0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.isPlaying())return!1;o0(this);this.startTime=a=g.Va();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.qC();this.Cj("play");-1==this.j&&this.Cj("resume");this.j=1;var b=g.Ra(this);b in m0||(m0[b]=this);MVa();NVa(this,a);return!0};
g.k.stop=function(a){o0(this);this.j=0;a&&(this.progress=1);OVa(this,this.progress);this.Cj("stop");this.Qy()};
g.k.pause=function(){this.isPlaying()&&(o0(this),this.j=-1,this.Cj("pause"))};
g.k.Y=function(){0==this.j||this.stop(!1);this.Cj("destroy");p0.Ee.Y.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.CE=function(){this.Cj("animate")};
g.k.Cj=function(a){this.dispatchEvent(new PVa(a,this))};
g.Wa(PVa,g.ve);g.Wa(q0,p0);q0.prototype.C=function(){};
q0.prototype.CE=function(){this.C();q0.Ee.CE.call(this)};
q0.prototype.Qy=function(){this.C();q0.Ee.Qy.call(this)};
q0.prototype.qC=function(){this.C();q0.Ee.qC.call(this)};
g.Wa(r0,q0);r0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(s0,g.I);s0.prototype.Ka=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.bt(a,b,c);this.j.push(a);return a};
s0.prototype.aC=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.Tpa(a,b,c);this.j.push(a);return a};
s0.prototype.pc=function(a){g.ct(a);g.ac(this.j,a)};
s0.prototype.Y=function(){g.ct(this.j);this.j.length=0;g.I.prototype.Y.call(this)};g.w(w0,g.PI);g.k=w0.prototype;g.k.load=function(){g.PI.prototype.load.call(this);if(!x0(this)){var a=g.cya(this.player.getVideoData());a?(a=v0(a,RVa(this)),y0(this,a,!1)):SVa(this)}};
g.k.unload=function(){y0(this,null);this.B&&(this.B.abort(),this.B=null);g.PI.prototype.unload.call(this)};
g.k.Wf=function(a,b){return x0(this)?"loadCustomEndscreenRenderer"===a?(a=v0(b,"new"),y0(this,a),!0):null:null};
g.k.getOptions=function(){return x0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.ub=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ZWa.length;f++){var h=Math.abs(b.width-ZWa[f]);if(-1===e||d>=h)e=f,d=h}d=$Wa[e];this.u&&g.Sk(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.bl(e.element,m,f);g.Yk(e.element,n,p);this.U&&(g.In(e.element,aXa),256<m||256<f?g.N(e.element,"ytp-ce-large-round"):96<m||96<f?g.N(e.element,"ytp-ce-medium-round"):g.N(e.element,"ytp-ce-small-round"));g.In(e.element,bXa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.In(e.element,$Wa);g.N(e.element,d);(e=g.mg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Sk(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())F0(this,this.endscreen.impressionUrls),(a=g.Gu())&&this.endscreen.visualElement&&g.Lu(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");F0(this,c.impressionUrls);(b=g.Gu())&&g.Lu(b,c.visualElement);this.player.S().B&&this.player.Ia("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Hn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Hn(b,"ytp-ce-shown");this.player.S().B&&this.player.Ia("endscreenelementhidden",a)}};
g.k.A_=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.In(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ZWa=[346,426,470,506,570,640,853,1280,1920],$Wa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),bXa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],aXa=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var bWa={Y6:"current",hda:"new"};var dWa={CLOSE:"close",Bda:"openUrl",SUBSCRIBE:"subscribe"},eWa={E3:"click",CLOSE:"close",E8:"hidden",mfa:"rollOut",nfa:"rollOver",nga:"shown"};var VWa={w2:"anchored",kS:"branding",CHANNEL:"channel",X6:"cta",H8:"highlightText",o$:"label",PLAYLIST:"playlist",xea:"popup",Ega:"speech",SUBSCRIBE:"subscribe",gha:"title",VIDEO:"video",Nia:"website"},UWa={kS:"branding",q3:"card",s7:"drawer",G8:"highlight",Zaa:"marker",Hea:"promotion",TEXT:"text",sja:"widget"};g.w(O0,g.I);g.k=O0.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.vv(a,b,{id:c,namespace:"annotations_module"});d&&this.Qa.set(a,d);e&&this.Ra.set(a,e);this.context.G.Sd([a])};
g.k.xz=function(){this.context.u.subscribe("resize",this.FA,this)};
g.k.DE=function(a,b,c,d,e,f){if(this.ib)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.xg(this.element)};
g.k.FA=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=H0(a);if(f){var h=nWa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.Tp(f||"");m&&n&&(n.v||n.list)?e.context.G.ll(n.v,b,n.list,!1):g.yH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d1(this.context.logger,c,l,d);mWa(f)||(c=g.Gu(),d=b.itct,c&&d&&g.Qu(c,g.zu(d)))}};
g.k.Y=function(){this.Qa.clear();this.Ra.clear();g.I.prototype.Y.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.w(T0,O0);g.k=T0.prototype;g.k.yp=function(){this.Z&&U0(this,this.Z)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.cl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.FA=function(){var a=this.isAvailable();g.dl(this.element,a);g.O(this.context.G.getRootNode(),g.uO.IV_DRAWER_ENABLED,a);k0(this.G)};
g.k.destroy=function(){this.G.Jv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.xt(this.V);g.ct(this.ma);this.Pa&&this.Pa.dispose();this.D&&this.D.dispose();O0.prototype.destroy.call(this)};
g.k.rV=function(){if(this.B){d1(this.context.logger,Y0(this).tracking.close);var a=g.Gu();a&&this.J&&g.Qu(a,this.J);S0(this)}};
g.k.EV=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.dX=function(){var a=g.Gu(),b=Y0(this);b=b?b.Ze:this.Ze;a&&b&&g.Ou(a,[b])};
g.k.cX=function(){var a=g.Gu(),b=Y0(this);b=b?b.Ze:this.Ze;a&&b&&g.Pu(a,[b])};
g.k.nU=function(){var a=Y0(this);d1(this.context.logger,a.tracking.sR);var b=g.Gu();b&&a&&g.Ou(b,[a.lj,a.Ze])};
g.k.eX=function(){var a=g.Gu(),b=Y0(this);a&&b&&g.Pu(a,[b.lj])};
g.k.mU=function(a){var b=Y0(this),c=g.Gu();this.j?a?(a=this.context.logger,d1(a,b.tracking.qD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.lj&&g.Qu(c,b.lj)):(a=this.context.logger,d1(a,b.tracking.qD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ze&&g.Qu(c,b.Ze)):(a=this.context.logger,d1(a,b.tracking.qD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ze&&g.Qu(c,this.Ze))};g.w(Z0,O0);Z0.prototype.xz=function(){O0.prototype.xz.call(this);CWa(this)};
Z0.prototype.show=function(){O0.prototype.show.call(this);var a=g.Gu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ou(a,[g.zu(b.itct)])};
Z0.prototype.hide=function(){O0.prototype.hide.call(this);var a=g.Gu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Pu(a,[g.zu(b.itct)])};g.w($0,Z0);
$0.prototype.show=function(){if(!this.isActive){Z0.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Aa:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.dl(this.u,!1);var b=this.context.environmentData.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Aa:["branding-img-container"]}):this.createElement({F:"button",Aa:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=iWa(this.annotation);c&&(b=this.context.environmentData.K("html5_player_branding_button_killswitch")?this.u:b,P0(this,b,c,this.annotation.id,a.session_data));GWa(this,a);this.J=!0}g.dl(this.element,!0);this.isActive=!0;this.u&&DWa(this,this.u)}};
$0.prototype.hide=function(){this.isActive&&(Z0.prototype.hide.call(this),g.dl(this.element,!1),this.isActive=!1)};
$0.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);Z0.prototype.destroy.call(this)};g.w(a1,Z0);g.k=a1.prototype;g.k.show=function(){this.isActive||(Z0.prototype.show.call(this),this.U||(IWa(this),this.U=!0),g.dl(this.element,!0),g.Xg(function(){g.Hn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,c1(this),JWa(this),KWa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.DE=function(a,b,c,d,e,f){return this.isCollapsed?!1:Z0.prototype.DE.call(this,a,b,c,d,e,f)};
g.k.kW=function(a){this.P=!0;b1(this,500,a)};
g.k.jW=function(){this.P=!1;LWa(this)};
g.k.eW=function(a){a.stopPropagation();this.hide()};
g.k.fW=function(a){a.stopPropagation();c1(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();Z0.prototype.destroy.call(this)};g.w(e1,g.PI);g.k=e1.prototype;g.k.Wf=function(a,b){if(!YWa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.CZ(b))&&f1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(sWa(this.j,b),k0(this.player)),!0}return null};
g.k.getOptions=function(){return YWa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Gs=function(){var a=this.player.S(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.CQ||a.V.get(b.videoId)||g.GD(b)||g.HD(b)?!0:!1};
g.k.uC=function(){if(this.B){var a=this.player.Wa().getVideoContentRect(!0);g.bl(this.B.element,a.width,a.height);g.Yk(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Ej();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.oU=function(a){OWa(this,a.state);g.V(a.state,2)&&(this.Rh()&&this.Pl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Jv(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.aq(h)&&h.responseXML?h.responseXML:null)&&(f1(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.PI.prototype.load.call(this);OWa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.fr()&&(a=QWa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().V.get(d);f&&RWa(e,f);f=f&&(f.KA||f.jx);if(!c.Xm||f)c.Qa?this.C=g.gq(c.Qa,e):(this.Jm=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Jm));
g.zI(this.player,this.B.element,4);this.uC();(f=g.GD(c))&&WWa(this,f);(f=g.HD(c))&&f.featuredChannel&&XWa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Qa&&(this.Jm&&(this.player.removeEventListener("videodatachange",this.Jm),this.Jm=null),this.C=g.gq(b.Qa,a))};
g.k.unload=function(){this.player.zf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,k0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.PI.prototype.unload.call(this);this.B.detach();this.Jm&&(this.player.removeEventListener("videodatachange",this.Jm),this.Jm=null)};
g.k.cQ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?SWa(this):this.load())};
g.k.Rh=function(){return!!this.j&&this.j.isAvailable()};
g.k.Pl=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Rh();this.j&&(a?c?R0(this.j,c,b):R0(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):S0(this.j))};
g.k.Jv=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Y=function(){this.player.S().V.unsubscribe("vast_info_card_add",this.cQ,this);g.Hn(this.player.getRootNode(),g.uO.IV_DRAWER_OPEN);for(var a=this.P,b=g.vn,c=0,d=a.length;c<d;c++)b.Aj(a[c]);this.P.length=0;g.PI.prototype.Y.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.OI("annotations_module",e1);g.OI("creatorendscreen",w0);})(_yt_player);
